name: Deploy Infrastructure

on: 
  pull_request:
    branches:
      - 'main'
  release:
    types:
      - published

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build Docker Image
    runs-on: kf-strides-linux-large
    env:
      AWS_REGION: "us-east-1"
    steps:
      - uses: actions/checkout@v3
      - name: Build and Publish
        run: ./deployment/scripts/cibuild ${{ env.AWS_REGION }}

  deploy-infra-qa:
    needs: [build]
    name: Deploy QA Infrastructure
    runs-on:  kf-strides-linux-large
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Terraform
        run: |
          install_with_retry() {
            max_attempts=5
            attempt_count=0
            success=false
            while [ $success = false ] && [ $attempt_count -le $max_attempts ]; do
              echo "Attempting $attempt_count/$max_attempts: Installing $*"
              sudo dnf install -y $*
            if [ $? -eq 0 ]; then
                success=true
              else
                echo "Failed to install $1 - retrying"
                attempt_count=$(( attempt_count + 1 ))
                sleep 5
              fi
            done
          }
          if ! command -v terraform &> /dev/null
            then
              install_with_retry yum-utils
              sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
              install_with_retry terraform
          fi
      - name: GitHub Auth 
        uses: mobiledevops/secret-to-file-action@v1
        with:
            base64-encoded-secret: ${{ secrets.D3B_AUTOMATION_ID_RSA }}
            filename: "id_rsa"
            is-executable: false 
            working-directory: "/home/ec2-user/.ssh"
      - name: Github Auth 
        run: |
          chmod 400 /home/ec2-user/.ssh/id_rsa
          ssh-keyscan -t rsa github.com > ~/.ssh/known_hosts
      - name: Terraform Plan
        env:
          ACCOUNT: "kf-strides" 
          ENVIRONMENT: "qa" 
          REGION: "us-east-1" 
        id: plan 
        run: | 
           ./deployment/scripts/infra plan
      - name: Terraform Apply
        env:
          ACCOUNT: "kf-strides" 
          ENVIRONMENT: "qa" 
          REGION: "us-east-1" 
        id: apply
        run: | 
           ./deployment/scripts/infra apply
  deploy-infra-prd:
    needs: [build]
    name: Deploy PRD Infrastructure
    runs-on:  kf-strides-linux-large
    if: ${{ github.event_name == 'release' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Terraform
        run: |
          install_with_retry() {
          max_attempts=5
          attempt_count=0
          success=false
          while [ $success = false ] && [ $attempt_count -le $max_attempts ]; do
            echo "Attempting $attempt_count/$max_attempts: Installing $*"
            sudo dnf install -y $*
          if [ $? -eq 0 ]; then
              success=true
            else
              echo "Failed to install $1 - retrying"
              attempt_count=$(( attempt_count + 1 ))
              sleep 5
            fi
          done
          }
          if ! command -v terraform &> /dev/null
            then
              install_with_retry yum-utils
              sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
              install_with_retry terraform       
          fi
      - name: GitHub Auth 
        uses: mobiledevops/secret-to-file-action@v1
        with:
            base64-encoded-secret: ${{ secrets.D3B_AUTOMATION_ID_RSA }}
            filename: "id_rsa"
            is-executable: false 
            working-directory: "/home/ec2-user/.ssh"
      - name: Github Auth 
        run: |
          chmod 400 /home/ec2-user/.ssh/id_rsa
          ssh-keyscan -t rsa github.com > ~/.ssh/known_hosts
      - name: Terraform Plan
        env:
          ACCOUNT: "kf-strides" 
          ENVIRONMENT: "prd" 
          REGION: "us-east-1" 
        id: plan 
        run: | 
           ./deployment/scripts/infra plan
      - name: Terraform Apply
        env:
          ACCOUNT: "kf-strides" 
          ENVIRONMENT: "prd" 
          REGION: "us-east-1" 
        id: apply
        run: | 
           ./deployment/scripts/infra apply
